Update build_ament_cmake.sh.in

diff --git a/vinca/templates/build_ament_cmake.sh.in b/vinca/templates/build_ament_cmake.sh.in
--- a/vinca/templates/build_ament_cmake.sh.in
+++ b/vinca/templates/build_ament_cmake.sh.in
@@ -39,11 +39,11 @@ fi;
 
 # Needed for qt-gui-cpp ..
 if [[ $target_platform =~ linux.* ]]; then
-  ln -s $GCC $BUILD_PREFIX/bin/gcc
-  ln -s $GXX $BUILD_PREFIX/bin/g++
+  ln -s $GCC $BUILD_PREFIX/bin/gcc || echo "Failed to create symlink to gcc"
+  ln -s $GXX $BUILD_PREFIX/bin/g++ || echo "Failed to create symlink to g++"
 else
-  ln -s $CC_FOR_BUILD $BUILD_PREFIX/bin/clang
-  ln -s $CXX_FOR_BUILD $BUILD_PREFIX/bin/clang++
+  ln -s $CC_FOR_BUILD $BUILD_PREFIX/bin/clang || echo "Failed to create symlink to clang"
+  ln -s $CXX_FOR_BUILD $BUILD_PREFIX/bin/clang++ || echo "Failed to create symlink to clang++"
 fi;
 
 cmake \
