Add macOS clang-scan-deps support

diff --git a/vinca/templates/build_ament_cmake.sh.in b/vinca/templates/build_ament_cmake.sh.in
--- a/vinca/templates/build_ament_cmake.sh.in
+++ b/vinca/templates/build_ament_cmake.sh.in
@@ -100,6 +100,18 @@ else
   export CMAKE_BLD="cmake"
 fi;
 
+CMAKE_CLANG_SCAN_DEPS_ARGS=()
+if [[ $target_platform =~ osx.* ]]; then
+  CLANG_SCAN_DEPS="$BUILD_PREFIX/bin/clang-scan-deps"
+  if [[ ! -x "$CLANG_SCAN_DEPS" ]]; then
+    echo "Missing executable clang-scan-deps at $CLANG_SCAN_DEPS" >&2
+    exit 1
+  fi
+  CMAKE_CLANG_SCAN_DEPS_ARGS+=(
+    "-DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS=$CLANG_SCAN_DEPS"
+  )
+fi
+
 if [ "${PKG_NAME}" == "@(ros_package_prefix)-rmw-wasm-cpp" ]; then
   WORK_DIR=$SRC_DIR/$PKG_NAME/src/work/rmw_wasm_cpp
 elif [ "${PKG_NAME}" == "@(ros_package_prefix)-wasm-cpp" ]; then
@@ -132,6 +144,7 @@ $CMAKE_GEN \
     -DCMAKE_OSX_DEPLOYMENT_TARGET=$OSX_DEPLOYMENT_TARGET \
     --compile-no-warning-as-error \
     $EXTRA_CMAKE_ARGS \
+    "${CMAKE_CLANG_SCAN_DEPS_ARGS[@@]}" \
     @(additional_cmake_args) \
     $WORK_DIR
 
diff --git a/vinca/templates/build_catkin.sh.in b/vinca/templates/build_catkin.sh.in
--- a/vinca/templates/build_catkin.sh.in
+++ b/vinca/templates/build_catkin.sh.in
@@ -81,6 +81,18 @@ if [[ $target_platform =~ emscripten.* ]]; then
   "
 fi
 
+CMAKE_CLANG_SCAN_DEPS_ARGS=()
+if [[ $target_platform =~ osx.* ]]; then
+  CLANG_SCAN_DEPS="$BUILD_PREFIX/bin/clang-scan-deps"
+  if [[ ! -x "$CLANG_SCAN_DEPS" ]]; then
+    echo "Missing executable clang-scan-deps at $CLANG_SCAN_DEPS" >&2
+    exit 1
+  fi
+  CMAKE_CLANG_SCAN_DEPS_ARGS+=(
+    "-DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS=$CLANG_SCAN_DEPS"
+  )
+fi
+
 export SKIP_TESTING=@(skip_testing)
 
 if [ "${PKG_NAME}" == "@(ros_package_prefix)-euslisp" ] || [ "${PKG_NAME}" = "@(ros_package_prefix)-jskeus" ] || [ "${PKG_NAME}" = "@(ros_package_prefix)-roseus" ]; then
@@ -109,6 +121,7 @@ cmake ${CMAKE_ARGS} --compile-no-warning-as-error \
          -DCATKIN_BUILD_BINARY_PACKAGE=$CATKIN_BUILD_BINARY_PACKAGE \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=$OSX_DEPLOYMENT_TARGET \
          $EXTRA_CMAKE_ARGS \
+         "${CMAKE_CLANG_SCAN_DEPS_ARGS[@@]}" \
          @(additional_cmake_args) \
          -G "$GENERATOR" \
          $SRC_DIR/$PKG_NAME/src/work/@(additional_folder)
